# Generated by Django 3.1.3 on 2020-11-29 00:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
