# Generated by Django 3.1.3 on 2020-11-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogarticle_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
