# Generated by Django 3.1.3 on 2020-11-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201128_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='category',
            field=models.CharField(choices=[('Django tutorial', 'Django tutorial'), ('News', 'News'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=200),
        ),
    ]
