# Generated by Django 2.0 on 2020-11-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='average_rating',
        ),
    ]
