# Generated by Django 2.1.5 on 2020-11-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=0.0, upload_to=''),
            preserve_default=False,
        ),
    ]
