# Generated by Django 2.1.5 on 2020-11-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20201128_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
