# Generated by Django 2.1.5 on 2020-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20201128_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
    ]
